algoritmo "exercicio3"
var
nota1,nota2,nota3,nota4,media:real
inicio


      escreva("digite a primeira nota: ")
      leia(nota1)
      
      escreva("digite a segunda nota: ")
      leia(nota2)
      
       escreva("digite a nota: ")
      leia(nota3)

      escreva("digite a  nota: ")
      leia(nota4)


      media := (nota1 + nota2 + nota3 + nota4)/4
      
      escreva("A média do aluno é: " , media)
fimalgoritmo