algoritmo "exercicio7"
var
idade:inteiro
salario:real
nome:caracter
inicio

      escreval("Informações")
      escreval("Digite o seu nome: ")
      leia(nome)
      
      escreval("digite sua idade: ")
      leia(idade)
      
      escreval("digite o segu salario")
      leia(salario)
      

      escreval("nome: " , nome)
      escreval("idade: " , idade)
      escreval("salrio: " , salario)

      


fimalgoritmo